server:
  port: 8182
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

tech:
  xavi:
    cfg:
      load-dataset: true